//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.22 at 07:44:59 AM EET 
//


package MyMessage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the MyMessage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MyMsg_QNAME = new QName("", "MyMsg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: MyMessage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link SingleMessage }
     * 
     */
    public SingleMessage createSingleMessage() {
        return new SingleMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Messages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MyMsg")
    public JAXBElement<Messages> createMyMsg(Messages value) {
        return new JAXBElement<Messages>(_MyMsg_QNAME, Messages.class, null, value);
    }

}
